### ISSUE TITLE
Is it possible to add "persistent repeat and shuffle" into YTM?

### ISSUE THREAD

**Issue by Raven-621** [Sv443/BetterYTM#101]
### Description of the feature:
When switching music, the status of repeat and shuffle resets (whether in home page, or in related tab (but i noticed if it's in up next tab, it doesn't reset). Is there a way to keep the current chosen status of repeat and shuffle the same when switching music?

### Other info / sketches:
Here's an example of repeat status resetted when music are switched (and different music was chosen from home page)

https://github.com/Sv443/BetterYTM/assets/141109979/c7cc5f93-8fc2-43a5-99fd-7cb4dc005f80

**Comment by Sv443** [comment]
Thanks for submitting a suggestion.  
Userscripts only have surface-level access to the site's own scripts, so the only other way is by observing changes to the document.  
Unfortunately those buttons don't have any language-independent attributes I could use to check which state they're currently in (nor at which point they are reset back to their "off" state), so I sadly don't see a way to do this.
