### ISSUE TITLE
Volume slider breaking at certain window width

### ISSUE THREAD

**Issue by Iftuga** [Sv443/BetterYTM#106]
### Checklist:

- [x] I checked [here](https://github.com/Sv443/BetterYTM/issues?q=is%3Aissue+sort%3Aupdated-desc) if there is already an issue for this bug
- [x] I am using the latest version of BetterYTM
- [x] I am using the latest version of my browser
- [x] I was able to reproduce the bug while all my other userscripts or extensions were disabled

### Description of the bug and steps to reproduce:

At a certain window width, the enhanced volume features stop working.
For example, I have the volume set to increase/decrease by 1% on scrolling, and when I reduce the width of a window with ytm (to fit my second monitor, which is in vertical position), the scroll increase/decrease reverts to 10%, and when I increase the width of the window again, it works again at 1%.
The threshold seems to be around 1000px in width.

### Environment:
- Browser name & version: Chromium 126.0.6478.231
- Userscript version & build number: v2.0.0 (#f449995a)

**Comment by Sv443** [comment]
Thanks for submitting the bug!  
Yeah it looks like YTM is switching to a different element if the screen width is too small and I haven't added my volume features to this secondary volume slider element.  
Should be an easy-ish fix, but I'll see if I can do it in [v2.1](https://github.com/Sv443/BetterYTM/pull/76) or in a patch to that version.

**Comment by Sv443** [comment]
I just fixed this issue and if you want and until v2.1.0 is released, you could install the preview version [here.](https://github.com/Sv443/BetterYTM/pull/76)  
Once v2.1.0 is out, you should manually remove and reinstall BetterYTM.

**Comment by Sv443** [comment]
My bad, that's fixed now.

**Comment by Sv443** [comment]
Hi again, I just released the new version 2.1.0 which includes this fix.  
You can install it from [GitHub](https://github.com/Sv443/BetterYTM/releases/tag/v2.1.0), [GreasyFork](https://greasyfork.org/en/scripts/475682-betterytm) or [OpenUserJS.](https://openuserjs.org/scripts/Sv443/BetterYTM)
