### ISSUE TITLE
help to extract queue header?

### ISSUE THREAD

**Issue by Gl17chV** [Sv443/BetterYTM#115]
Hi dev 👋

I recently changed Violentmonkey to FireMonkey because it uses firefox api and to get rid of stylus. All scripts and css work fine except yours. However, I won't be inconsiderate in asking for FireMonkey support as that would take a rewrite of the script and all just for a random guy plus not all the functionality would work and that would throw away all your work, but the only thing I really need from your script is the queue header that appears in the song lists, as due to some bad scripting in ytm on touchscreen; when you slide in the queue list it moves songs instead of scrolling, the only way I can scroll is by sliding the queue header of your userscript. I don't really use the other functions or even the header buttons and I would really like to extract that function from your script however java is out of my knowledge and it is hard to read the code and I don't know if that function is the one that creates malfunctioning in FireMonkey.

I just asking for help to integrate this functionality or if this causes incompatibility. I hope this is not a bother for you and will fully understand no help or response from you as this is a mere whim of mine unrelated to your work.

Btw I contemplated the idea of making a scroll bar but webkit is very limited firefox.

**Comment by Sv443** [comment]
Thanks for submitting an issue, I commented on the one you made in the FireMonkey repo: https://github.com/erosman/support/issues/659  
  
I don't quite understand, do you want me to make it possible to entirely remove the header or to revert it back to how it is when you don't have the userscript installed?

**Comment by Gl17chV** [comment]
Thanks for your answer, I mean to make a script that only has the header of the queue list.

![Screenshot_2024-10-18-10-51-27](https://github.com/user-attachments/assets/b71622ae-6431-42d3-9488-a08190ee68ca)

**Comment by Sv443** [comment]
Hmm the only thing I can think of is if you go into the configuration menu and disable all features except that one. Detaching that feature would probably be too difficult because of how integrated everything is.

**Comment by Gl17chV** [comment]
I see, well, thank btw for replying

**Comment by Sv443** [comment]
Quick follow-up, BetterYTM will not work under FireMonkey because of the way that extension runs userscripts and I doubt there is a fix for that.  
Unfortunately you're gonna have to either not use BetterYTM or switch to another extension.
