### ISSUE TITLE
A button to remove songs from the playlist

### ISSUE THREAD

**Issue by M3tR3mix** [Sv443/BetterYTM#39]
Would be even better if the button was placed like the remove song from queue button and not in the right click menu

**Comment by Sv443** [comment]
Thanks for submitting an issue! I was thinking about adding the current queue buttons to all song list types so this is definitely something I wanna add.

**Comment by Sv443** [comment]
The new version including your feature request is now published on [GitHub](https://github.com/Sv443/BetterYTM?tab=readme-ov-file#installation), [GreasyFork](https://greasyfork.org/en/scripts/475682-betterytm) and [OpenUserJS](https://openuserjs.org/scripts/Sv443/BetterYTM) :)
